### ISSUE TITLE
Missing comments

### ISSUE THREAD

**Issue by arienshibani** [mongolyy/reviewdog-action-biome#43]
# Action suggest many changes, but no comments
I reckon i am missing some sort of setting in my YAML file?

```
name:  Reviewdog
on: workflow_dispatch
jobs:
  biome:
    name: Linter 🧹
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
      - name: lint
        uses: mongolyy/reviewdog-action-biome@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
```

This is what i am trying to achieve:

![image](https://github.com/mongolyy/reviewdog-action-biome/assets/22197324/20a232f8-aecd-4126-9669-39328b3d58cb)
