### ISSUE TITLE
False positive after committing a suggestion

### ISSUE THREAD

**Issue by informeti** [mongolyy/reviewdog-action-biome#66]
I just tried out this action, and formatting and reporting both seem to work out-of-the-box. Excellent!

But when I committed the suggestion in GitHub, the changed lines were reported again as an error, except that the diff doesn't really show a difference.

It _seems_ to be due to a missing line at the end of the file, which Biome seems to unconditionally require... If my understanding is correct, this action, reviewdog or biome strips the empty line at the end of the file.

Truth be told, I'd rather have Biome accept this, but afaik Biome is a bit conservative on that side of things.

---

**Before committing the suggestion (so far, so good)**:
![image](https://github.com/user-attachments/assets/a852da9e-d7aa-418e-9366-bdf05280f118)

**After committing the suggestion (not good)**:
![image](https://github.com/user-attachments/assets/46ee97a6-ef74-42c2-b4ff-19d819e97e3a)

Workflow file:

```yaml
name: check

on:
  pull_request:

jobs:
  biome:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
```

Log:

```
Run mongolyy/reviewdog-action-biome@v1
Run biomejs/setup-biome@v2.2.1
Run reviewdog/action-setup@v1.3.0
Run set -eu
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
Run set -eu
📖 reviewdog -h
Run $GITHUB_ACTION_PATH/script.sh
 Running Biome with reviewdog 🐶 ...
Run reviewdog/action-suggester@v1
Run set -euo pipefail
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
Run set -euo pipefail
📖 reviewdog -h
Run set -euo pipefail
  set -euo pipefail
  . "$GITHUB_ACTION_PATH/script.sh"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_GITHUB_TOKEN: ***
    INPUT_TOOL_NAME: Biome
    INPUT_LEVEL: error
    INPUT_FILTER_MODE: added
    INPUT_FAIL_ON_ERROR: true
    INPUT_REVIEWDOG_FLAGS: 
    INPUT_CLEANUP: true
Saved working directory and index state WIP on (no branch): 57a96d7 Merge 9fc052bdd7b9084[33](snip#step:3:39)30de0bbc456e6ccb9436770 into 560b9777d43c5fa6cc80342c6fd4fa50e878fe28
ops/main.ts:3:-export * as organization from "./organization/main";
ops/main.ts:3:+export * as organization from "./organization/main";
reviewdog: input data has violations
Error: Process completed with exit code 1.
```

---

PS: Thank you for this wonderful action!
