### ISSUE TITLE
Help needed (most likely user error)

### ISSUE THREAD

**Issue by tzmara** [mongolyy/reviewdog-action-biome#85]
Our github action looks similar to this (shortened to the relevant part):

```
name: Check Bull Requests
on: [pull_request]
jobs:
  biome-reviewdog:
    name: Check format for changed files
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          biome_flags: --formatter-enabled=true --organize-imports-enabled=true --linter-enabled=true .
          filter_mode: diff_context
          fail_level: any

  biome-direct:
    name: Lint changed files
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome on Changed Files
        run:
          biome ci --formatter-enabled=true --organize-imports-enabled=true --linter-enabled=true $(git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }})
```

- biome-reviewdog is never reporting anything or failing
- biome0-direct fails on formatting or linting issues

Reason for `--formatter-enabled...` etc. is to have them run as seperate tasks.

I also tried:
- without . in biome flags
- different levels
- different fail_levels (and had the deprecated older fail-on-error as well)

Most likely it's something I feel stupid about afterwards, but can anyone see the problem?
